print("Hello, student. What is your name?")
name = input("My name is ")
print(f"Hello {name}. Do you often find yourself talking over others?")
ans1 = input()
print("Okay. Do you see yourself able to pay attention in class?")
ans2 = input()
print("Okay. Do you feel okay with asking someone for help if needed?")
ans3 = input()
print("Okay. Are you able to handle bullying without fighting back?")
ans4 = input()
print("Okay, last question: Do you feel your future depends on your grades here?")
ans5 = input()
print(f"Okay, so just to be clear, you answered \"{ans1}\" to the first question,\"{ans2}\" to the second \"{ans3}\" to the third question, \"{ans4}\" to the fourth question, and \"{ans5}\" to the last question.\nDid I get that correctly?")
yesOrNo = input()
print("Got it. Welcome to Osbourn :)")